include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - backend/**
    - build/**
    - android/**
    - ios/**
    - web/**
    - windows/**
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
